### ISSUE TITLE
Using custom fields (NString) in "Jira Comment Hint" plugin in GitExtensions

### ISSUE THREAD

**Issue by zroytman** [thomaslevesque/NString#13]
Hi, i'm using GitExtensions 3.1.1 and have a placeholder {CustomFields} in the Jira Hint Comment plugin definition. Using this placeholder as is returns me the message that this is a collection. How can i specify the custom field from this collection? The required custom field is "Application". Tried several ways like {CustomFields["Application"]}, {CustomFields("Application")}. {CustomFields.Application}, etc... getting error messages.
According to the following link the CustomFIelds is the NString which can only get fields and properties from top level object.

https://github.com/gitextensions/gitextensions/issues/6154#issuecomment-502978414

Please help to solve the issue.
Thanks.

**Comment by thomaslevesque** [comment]
Hi @zroytman,
This isn't supported right now. It could probably be done, but it's a significant amount of work. I'll create a backlog issue for this, but I can't commit to a release date... I'll gladly accept contributions, though.

**Comment by thomaslevesque** [comment]
Closing this issue in favor of https://github.com/thomaslevesque/NString/issues/14
