### ISSUE TITLE
Do not use a regex to validate e-mail addresses

### ISSUE THREAD

**Issue by RobThree** [thomaslevesque/NString#3]
[This](https://github.com/thomaslevesque/NString/blob/16729796e76cac8d8889a3d045f3398c413c47a3/NString/StringExtensions.cs#L275) is a bad idea. The regex will fail, amongst others, all these [valid](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains) TLD's:
1. .academy
2. .accountant
3. .accountants
4. .airforce
5. .apartments
6. .associates
7. .attorney
8. .auction
9. .bargains
10. .blackfriday
11. .boutique
12. .builders
13. .business
14. .cancerresearch
15. .capital
16. .careers
17. .catering
18. .channel
19. .christmas
20. .cleaning
21. .clothing
22. .college
23. .community
24. .company
25. .computer
26. .construction
27. .consulting
28. .contractors
29. .cooking
30. .country
31. .coupons
32. .creditcard
33. .cricket
34. .cruises
35. .delivery
36. .democrat
37. .dentist
38. .diamonds
39. .digital
40. .directory
41. .discount
42. .domains
43. .download
44. .education
45. .engineer
46. .engineering
47. .equipment
48. .exchange
49. .exposed
50. .express
51. .fashion
52. .finance
53. .financial
54. .fishing
55. .fitness
56. .flights
57. .florist
58. .flowers
59. .football
60. .forsale
61. .foundation
62. .furniture
63. .gallery
64. .graphics
65. .guitars
66. .healthcare
67. .holdings
68. .holiday
69. .hosting
70. .institute[59]
71. .international
72. .investments
73. .jewelry
74. .kitchen
75. .lighting
76. .limited
77. .management
78. .marketing
79. .markets
80. .memorial
81. .mortgage
82. .motorcycles
83. .network
84. .organic
85. .partners
86. .pharmacy
87. .photography
88. .pictures
89. .feedback
90. .plumbing
91. .productions
92. .properties
93. .property
94. .recipes
95. .rentals
96. .republican
97. .reviews
98. .science
99. .services
100. .singles
101. .software
102. .solutions
103. .supplies
104. .support
105. .surgery
106. .systems
107. .technology
108. .theater
109. .training
110. .university
111. .vacations
112. .website
113. .wedding
114. .whoswho

Since validating an e-mail address is [_very_ hard](http://stackoverflow.com/a/201378/215042), you're better off [sending a confirmation link](https://davidcel.is/posts/stop-validating-email-addresses-with-regex/).

Having an (extension) method that "promises" (by it's name alone) to check validity of an e-mail address should either work reliably or not exist at all.

Having said that; I also think it shouldn't be in this library at all; all other methods (as far as I've seen) provide string (handy) operations that the BCL doesn't provide for whatever reason. `IsValidEmail` is not in the same (sub)set of all the operations and it feels _slapped on, because we can_: "Hey, `IsValidEmail` may come in handy, let's put it in!". This library, IMHO ofcourse(!), should focus on string operations that can be applied on any "generic" string. You could even argue that an e-mailaddress should have it's own type like `Uri` but that's a whole other discussion. But if it had, then _that_ would be the place to have an `IsValidEmail` (extension) method.

> A good extension method should:
> - Apply to any possible instance of the type it extends.
> - Simplify logic and improve readability/maintainability.
> - **Apply to the most specific type or interface applicable.**
> - Be isolated in a namespace so that it does not pollute IntelliSense.

([Source](http://geekswithblogs.net/BlackRabbitCoder/archive/2010/04/26/c-extension-methods---to-extend-or-not-to-extend.aspx))

**Comment by thomaslevesque** [comment]
Hi @RobThree,

All fair points. I agree that `IsValidEmail` doesn't really belong in here, and if I wrote the library today, I wouldn't include it. That being said, I'm not going to remove it for now, because it would be a breaking change for people using it. I can deprecate it, though; and if I ever release another major version (pretty unlikely, but who knows...), I will remove it.

In the meantime, I guess I could try to improve the regex; I know it's not the ideal way to validate an email address, but at least I could change it to support the new TLDs.

> Since validating an e-mail address is very hard, you're better off sending a confirmation link.

Actually, the method isn't very well named; it doesn't check that the address exists, but only that it's well formed. It should probably be named `IsWellFormedEmail` instead. Obviously, a confirmation link is necessary if you want to check that the address exists, but sometimes you don't want to (or can't) wait for the user to click the confirmation link (which is a valid approach only for web apps anyway).

**Comment by thomaslevesque** [comment]
> I can deprecate it, though; and if I ever release another major version (pretty unlikely, but who knows...), I will remove it.

Well, the unlikely happened. I strong-named the assembly, which is a breaking change, so I bumped the version to 2.0.0 and took the opportunity to remove `IsValidEmail`.

**Comment by RobThree** [comment]
It's still mentioned [in the README](https://github.com/thomaslevesque/NString/tree/6b4e1bfd1e25d473f854c23869787783a57c6993#isvalidemail). Not sure if that's intentional but you may want to take it out?

**Comment by thomaslevesque** [comment]
Oops. Thanks, I'll remove it.
